# Generated by Django 3.2.4 on 2021-06-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default-profile.png', null=True, upload_to=''),
        ),
    ]
